version: '3.7'

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    image: client-server
    container_name: my-client-server
    command: npm start
    volumes:
      - ./client:/usr/app
      - node_modules:/usr/app/node_modules
    ports:
      - "3000:3000"

volumes:
    node_modules: